version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
    depends_on:
      - backend