spring:
  application:
    name: duke
  datasource:
    url: jdbc:h2:./assistant;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  ai:
    ollama:
      base-url: http://192.168.1.107:11434
      chat:
        options:
          model: llama3
          temperature: 0.3
        answer:
          options:
            model: llama3
            temperature: 0.4
        deterministic:
          options:
            model: llama3
            temperature: 0.0

  mvc:
    static-path-pattern: /static/**
    cors:
      allowed-origins: "*"
      allow-credentials: true
      allowed-methods: GET, POST, PUT, DELETE, OPTIONS
      allowed-headers: "*"
  webflux:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/



  threads:
    virtual:
      enabled: true