# Input
Following is a conversation between an ai assistant and a human(User).

**Chat History:**
- assistant: Hello. How can i help you?
{chatHistoryStr}
**Follow-Up Question:**
- human: {question}

# Task
Using the chat history and the follow-up question provided, rephrase the follow-up question into a standalone question that can be understood without chat history.

Do NOT provide any comments just give the standalone question.
Standalone Question: